/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.74.0
  Forc version: 0.50.0
  Fuel-Core version: 0.22.1
*/

export type { AirbnbContractAbi } from './AirbnbContractAbi';

export { AirbnbContractAbi__factory } from './factories/AirbnbContractAbi__factory';
